POST http://localhost:8000/bands
Content-Type: application/json

{
    "name": "Barsuk",
    "genre": "elecronic",
    "albums": [
        {
            "title": "son na snegu",
            "release_date": "2020-02-04"
        },
    ]
}

###
GET http://localhost:8000/bands
